"""Unique publisher name

Revision ID: 00fc51feeafe
Revises: 727150a7de8f
Create Date: 2025-02-25 23:32:04.752947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fc51feeafe'
down_revision: Union[str, None] = '727150a7de8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'publishers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publishers', type_='unique')
    # ### end Alembic commands ###
