"""Uniq book fields combination

Revision ID: 01d6b9982f25
Revises: 52b046c68e63
Create Date: 2025-02-26 19:52:47.791841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d6b9982f25'
down_revision: Union[str, None] = '52b046c68e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_book_instance', 'books', ['publisher_code', 'author_code', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_book_instance', 'books', type_='unique')
    # ### end Alembic commands ###
