"""Publisher Table

Revision ID: 17c51778eea0
Revises: ef380c5054ba
Create Date: 2025-02-25 17:33:06.857285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c51778eea0'
down_revision: Union[str, None] = 'ef380c5054ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('code', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('publisher_code_idx', 'publishers', ['code'], unique=False, postgresql_using='hash')
    op.create_index('publishers_name_idx', 'publishers', ['name'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('publishers_name_idx', table_name='publishers', postgresql_using='hash')
    op.drop_index('publisher_code_idx', table_name='publishers', postgresql_using='hash')
    op.drop_table('publishers')
    # ### end Alembic commands ###
