"""issuance expiration

Revision ID: 275fe2e0f666
Revises: 01d6b9982f25
Create Date: 2025-02-26 19:57:41.817001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275fe2e0f666'
down_revision: Union[str, None] = '01d6b9982f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issuances', sa.Column('issuanced_at', sa.Date(), nullable=False))
    op.add_column('issuances', sa.Column('expires_at', sa.Date(), nullable=False))
    op.drop_index('issuance_date_idx', table_name='issuances')
    op.create_index('issuance_date_idx', 'issuances', ['issuanced_at'], unique=False)
    op.create_index('issuance_expiration_date_idx', 'issuances', ['expires_at'], unique=False)
    op.drop_column('issuances', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issuances', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index('issuance_expiration_date_idx', table_name='issuances')
    op.drop_index('issuance_date_idx', table_name='issuances')
    op.create_index('issuance_date_idx', 'issuances', ['date'], unique=False)
    op.drop_column('issuances', 'expires_at')
    op.drop_column('issuances', 'issuanced_at')
    # ### end Alembic commands ###
