"""Column attributes

Revision ID: 3891e8e1f43b
Revises: 00fc51feeafe
Create Date: 2025-02-26 17:04:05.292386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3891e8e1f43b'
down_revision: Union[str, None] = '00fc51feeafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('books', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('books', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'books', ['title'])
    op.alter_column('readers', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readers', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'books', type_='unique')
    op.alter_column('books', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('books', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
