"""Authors Table

Revision ID: 990057c9ea0a
Revises: 17c51778eea0
Create Date: 2025-02-25 17:36:20.659299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990057c9ea0a'
down_revision: Union[str, None] = '17c51778eea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('code', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('author_code_idx', 'authors', ['code'], unique=False, postgresql_using='hash')
    op.create_index('author_name_idx', 'authors', ['name'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('author_name_idx', table_name='authors', postgresql_using='hash')
    op.drop_index('author_code_idx', table_name='authors', postgresql_using='hash')
    op.drop_table('authors')
    # ### end Alembic commands ###
