"""Readers Table

Revision ID: a0faf2ded155
Revises: a336c9f31505
Create Date: 2025-02-25 17:51:28.102529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0faf2ded155'
down_revision: Union[str, None] = 'a336c9f31505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('code', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.CheckConstraint("phone ~ '^\\+\\d{1,3}\\(\\d{1,4}\\)\\d{3}-\\d{2}-\\d{2}$'", name='check_phone_format'),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('reader_code_idx', 'readers', ['code'], unique=False, postgresql_using='hash')
    op.create_index('reader_full_name_idx', 'readers', ['full_name'], unique=False, postgresql_using='hash')
    op.create_index('reader_phone_idx', 'readers', ['phone'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('reader_phone_idx', table_name='readers', postgresql_using='hash')
    op.drop_index('reader_full_name_idx', table_name='readers', postgresql_using='hash')
    op.drop_index('reader_code_idx', table_name='readers', postgresql_using='hash')
    op.drop_table('readers')
    # ### end Alembic commands ###
