"""Books Table

Revision ID: a336c9f31505
Revises: 990057c9ea0a
Create Date: 2025-02-25 17:46:27.221595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a336c9f31505'
down_revision: Union[str, None] = '990057c9ea0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('code', sa.UUID(), nullable=False),
    sa.Column('publisher_code', sa.UUID(), nullable=False),
    sa.Column('author_code', sa.UUID(), nullable=False),
    sa.Column('publishing_year', sa.SmallInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_amount_non_negative'),
    sa.CheckConstraint('price > 0', name='check_price_non_negative'),
    sa.CheckConstraint('publishing_year > 0 AND publishing_year < 10000', name='check_publishing_year_correct'),
    sa.ForeignKeyConstraint(['author_code'], ['authors.code'], ),
    sa.ForeignKeyConstraint(['publisher_code'], ['publishers.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('book_amount_idx', 'books', ['amount'], unique=False)
    op.create_index('book_price_idx', 'books', ['price'], unique=False)
    op.create_index('book_publishing_year_idx', 'books', ['publishing_year'], unique=False)
    op.create_index('book_title_idx', 'books', ['title'], unique=False, postgresql_using='hash')
    op.create_index('books_code_idx', 'books', ['code'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('books_code_idx', table_name='books', postgresql_using='hash')
    op.drop_index('book_title_idx', table_name='books', postgresql_using='hash')
    op.drop_index('book_publishing_year_idx', table_name='books')
    op.drop_index('book_price_idx', table_name='books')
    op.drop_index('book_amount_idx', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
