"""Readers Table

Revision ID: be154ca65300
Revises: a0faf2ded155
Create Date: 2025-02-25 18:08:05.529223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be154ca65300'
down_revision: Union[str, None] = 'a0faf2ded155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuances',
    sa.Column('code', sa.UUID(), nullable=False),
    sa.Column('reader_code', sa.UUID(), nullable=False),
    sa.Column('book_code', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_code'], ['books.code'], ),
    sa.ForeignKeyConstraint(['reader_code'], ['readers.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('issuance_date_idx', 'issuances', ['date'], unique=False)
    op.create_index('issuances_code_idx', 'issuances', ['code'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('issuances_code_idx', table_name='issuances', postgresql_using='hash')
    op.drop_index('issuance_date_idx', table_name='issuances')
    op.drop_table('issuances')
    # ### end Alembic commands ###
